name: process_singlecell_broadinstitute
namespace: datasets/workflows

argument_groups:
  - name: Inputs
    arguments:
      - type: file
        name: --raw_data_dir
        description: |
          Path to the single-cell dataset dir.

          This directory is obtained by browsing one of the datasets on the single cell broad institute website and clicking 'Bulk download' and downloading the curl config file but not yet downloading the individual files.

          Example: https://singlecell.broadinstitute.org/single_cell/study/SCP2162/slide-tags-snrna-seq-on-mouse-hippocampus#study-download
        example: resources/raw_data/singlecell_broadinstitute/SCP2167
        required: true
        direction: input
  - name: Metadata
    arguments:
      - type: string
        name: --id
        description: "A unique identifier for the dataset"
        required: true
      - name: --dataset_name
        type: string
        description: Nicely formatted name.
        required: true
      - type: string
        name: --dataset_url
        description: Link to the original source of the dataset.
        required: false
      - name: --dataset_reference
        type: string
        description: Bibtex reference of the paper in which the dataset was published.
        required: false
      - name: --dataset_summary
        type: string
        description: Short description of the dataset.
        required: true
      - name: --dataset_description
        type: string
        description: Long description of the dataset.
        required: true
      - name: --dataset_organism
        type: string
        description: The organism of the sample in the dataset.
        required: false
  - name: Sampling options
    arguments:
      - name: "--do_subsample"
        type: boolean
        default: false
        description: "Whether or not to subsample the dataset"
      - name: "--n_obs"
        type: integer
        description: Maximum number of observations to be kept. It might end up being less because empty cells / genes are removed.
        default: 500
      - name: "--n_vars"
        type: integer
        description: Maximum number of variables to be kept. It might end up being less because empty cells / genes are removed.
        default: 500
      - name: "--keep_features"
        type: string
        multiple: true
        description: A list of genes to keep.
      - name: "--keep_cell_type_categories"
        type: "string"
        multiple: true
        description: "Categories indexes to be selected"
        required: false
      - name: "--keep_batch_categories"
        type: "string"
        multiple: true
        description: "Categories indexes to be selected"
        required: false
      - name: "--even"
        type: "boolean_true"
        description: Subsample evenly from different batches
      - name: "--seed"
        type: "integer"
        description: "A seed for the subsampling."
        example: 123
  - name: Outputs
    arguments:
    - name: "--output_dataset"
      __merge__: /src/api/file_common_spatial.yaml
      direction: output
      required: true
      default: "$id/dataset.h5ad"
    - name: "--output_meta"
      direction: "output"
      type: file
      description: "Dataset metadata"
      default: "$id/dataset_meta.yaml"

resources:
  - type: nextflow_script
    path: main.nf
    entrypoint: run_wf
  - path: /common/nextflow_helpers/helper.nf

dependencies:
  - name: datasets/loaders/singlecell_broadinstitute
  - name: datasets/processors/subsample
    repository: openproblems
  - name: datasets/normalization/log_cp
    repository: openproblems
  - name: datasets/processors/pca
    repository: openproblems
  - name: datasets/processors/hvg
    repository: openproblems
  - name: datasets/processors/knn
    repository: openproblems
  - name: h5ad/extract_uns_metadata
    repository: core

runners:
  - type: nextflow
    directives:
      label: [midcpu, midmem, hightime]
