__merge__: /src/api/comp_dataset_loader.yaml

name: download
arguments:
  - type: file
    name: --dataset_curl_config
    description: |
      Path to the single-cell dataset curl config file as provided by the Broad Institute.

      This file is obtained by browsing one of the datasets on the single cell broad institute website and clicking 'Bulk download' and downloading the curl config file but not yet downloading the individual files.

      Example: https://singlecell.broadinstitute.org/single_cell/study/SCP2162/slide-tags-snrna-seq-on-mouse-hippocampus#study-download
    example: resources/datasets/raw/singlecell_broadinstitute_configs/SCP2162.txt
    required: true
    direction: input
resources:
  - type: python_script
    path: script.py
engines:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.4
runners:
  - type: executable
  - type: nextflow