name: "download_singlecell_broadinstitute_dataset"
namespace: "dataset_loaders"
version: "build_main"
argument_groups:
- name: "Inputs"
  arguments:
  - type: "file"
    name: "--dataset_curl_config"
    description: "Path to the single-cell dataset curl config file as provided by\
      \ the Broad Institute.\n\nThis file is obtained by browsing one of the datasets\
      \ on the single cell broad institute website and clicking 'Bulk download' and\
      \ downloading the curl config file but not yet downloading the individual files.\n\
      \nExample: https://singlecell.broadinstitute.org/single_cell/study/SCP2162/slide-tags-snrna-seq-on-mouse-hippocampus#study-download\n"
    info: null
    example:
    - "resources/datasets/raw/singlecell_broadinstitute_configs/SCP2162.txt"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
- name: "Metadata"
  arguments:
  - type: "string"
    name: "--dataset_id"
    description: "Unique identifier for the dataset."
    info: null
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--dataset_name"
    description: "Nicely formatted name."
    info: null
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--dataset_url"
    description: "Link to the original source of the dataset."
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--dataset_reference"
    description: "Bibtex reference of the paper in which the dataset was published."
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--dataset_summary"
    description: "Short description of the dataset."
    info: null
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--dataset_description"
    description: "Long description of the dataset."
    info: null
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--dataset_organism"
    description: "The organism of the dataset."
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
- name: "Outputs"
  arguments:
  - type: "file"
    name: "--output"
    description: "The downloaded dataset with metadata in uns."
    info: null
    example:
    - "dataset.h5ad"
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ";"
resources:
- type: "python_script"
  path: "script.py"
  is_executable: true
test_resources:
- type: "python_script"
  path: "run_and_check_output.py"
  is_executable: true
info: null
status: "enabled"
license: "MIT"
links:
  repository: "https://github.com/openproblems-bio/task_cell_cell_communication"
  docker_registry: "ghcr.io"
runners:
- type: "executable"
  id: "executable"
  docker_setup_strategy: "ifneedbepullelsecachedbuild"
- type: "nextflow"
  id: "nextflow"
  directives:
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      mem1gb: "memory = 1000000000.B"
      mem2gb: "memory = 2000000000.B"
      mem5gb: "memory = 5000000000.B"
      mem10gb: "memory = 10000000000.B"
      mem20gb: "memory = 20000000000.B"
      mem50gb: "memory = 50000000000.B"
      mem100gb: "memory = 100000000000.B"
      mem200gb: "memory = 200000000000.B"
      mem500gb: "memory = 500000000000.B"
      mem1tb: "memory = 1000000000000.B"
      mem2tb: "memory = 2000000000000.B"
      mem5tb: "memory = 5000000000000.B"
      mem10tb: "memory = 10000000000000.B"
      mem20tb: "memory = 20000000000000.B"
      mem50tb: "memory = 50000000000000.B"
      mem100tb: "memory = 100000000000000.B"
      mem200tb: "memory = 200000000000000.B"
      mem500tb: "memory = 500000000000000.B"
      mem1gib: "memory = 1073741824.B"
      mem2gib: "memory = 2147483648.B"
      mem4gib: "memory = 4294967296.B"
      mem8gib: "memory = 8589934592.B"
      mem16gib: "memory = 17179869184.B"
      mem32gib: "memory = 34359738368.B"
      mem64gib: "memory = 68719476736.B"
      mem128gib: "memory = 137438953472.B"
      mem256gib: "memory = 274877906944.B"
      mem512gib: "memory = 549755813888.B"
      mem1tib: "memory = 1099511627776.B"
      mem2tib: "memory = 2199023255552.B"
      mem4tib: "memory = 4398046511104.B"
      mem8tib: "memory = 8796093022208.B"
      mem16tib: "memory = 17592186044416.B"
      mem32tib: "memory = 35184372088832.B"
      mem64tib: "memory = 70368744177664.B"
      mem128tib: "memory = 140737488355328.B"
      mem256tib: "memory = 281474976710656.B"
      mem512tib: "memory = 562949953421312.B"
      cpu1: "cpus = 1"
      cpu2: "cpus = 2"
      cpu5: "cpus = 5"
      cpu10: "cpus = 10"
      cpu20: "cpus = 20"
      cpu50: "cpus = 50"
      cpu100: "cpus = 100"
      cpu200: "cpus = 200"
      cpu500: "cpus = 500"
      cpu1000: "cpus = 1000"
  debug: false
  container: "docker"
engines:
- type: "docker"
  id: "docker"
  image: "ghcr.io/openproblems-bio/base_python:1.0.4"
  namespace_separator: "/"
  entrypoint: []
  cmd: null
build_info:
  config: "src/dataset_loaders/download_singlecell_broadinstitute_dataset/config.vsh.yaml"
  runner: "nextflow"
  engine: "docker"
  output: "target/nextflow/dataset_loaders/download_singlecell_broadinstitute_dataset"
  executable: "target/nextflow/dataset_loaders/download_singlecell_broadinstitute_dataset/main.nf"
  viash_version: "0.9.0-RC7"
  git_commit: "6dd67c464127defc2b827d2e28817b093048b925"
  git_remote: "https://github.com/openproblems-bio/task_cell_cell_communication"
package_config:
  name: "task_cell_cell_communication"
  version: "build_main"
  label: "Cell-Cell Communication"
  summary: "Predicting cell-cell interactions between source cell types and target\
    \ cell types."
  description: "The growing availability of single-cell data has sparked an increased\
    \ interest in the inference of cell-cell communication (CCC),\nwith an ever-growing\
    \ number of computational tools developed for this purpose.\n\nDifferent tools\
    \ propose distinct preprocessing steps with diverse scoring functions that are\
    \ challenging to compare and evaluate.\nFurthermore, each tool typically comes\
    \ with its own set of prior knowledge. To harmonize these,\nDimitrov et al recently\
    \ developed the [LIANA+](https://github.com/saezlab/liana-py) framework, which\
    \ was used as a foundation for this task.\n\nThe challenges in evaluating the\
    \ tools are further exacerbated by the lack of a gold standard to benchmark the\
    \ performance of CCC\nmethods. In an attempt to address this, Dimitrov et al use\
    \ alternative data modalities, including the spatial proximity of cell types\n\
    and downstream cytokine activities, to generate an inferred ground truth. However,\
    \ these modalities are only approximations of\nbiological reality and come with\
    \ their own assumptions and limitations. In time, the inclusion of more datasets\
    \ with known ground\ntruth interactions will become available, from which the\
    \ limitations and advantages of the different CCC methods will be better understood.\n\
    This subtask evaluates methods in their ability to predict interactions between\
    \ spatially-adjacent source cell types and target\ncell types. This subtask focuses\
    \ on the prediction of interactions from steady-state, or single-context, single-cell\
    \ data.\n"
  info:
    image: "thumbnail.svg"
    v1:
      path: "openproblems/tasks/_cell_cell_communication/cell_cell_communication_source_target/README.md"
      commit: "637163f"
    test_resources:
    - type: "s3"
      path: "s3://openproblems-data/resources/cell_cell_communication"
      dest: "resources"
  viash_version: "0.9.0-RC7"
  source: "src"
  target: "target"
  authors:
  - name: "Daniel Dimitrov"
    roles:
    - "maintainer"
    - "author"
    info:
      github: "dbdimitrov"
  - name: "Scott Gigante"
    roles:
    - "contributor"
    info:
      github: "scottgigante"
      orcid: "0000-0002-4544-2764"
  - name: "Daniel Strobl"
    roles:
    - "contributor"
    info:
      github: "danielStrobl"
  - name: "Robrecht Cannoodt"
    roles:
    - "contributor"
    info:
      github: "rcannood"
      orcid: "0000-0003-3641-729X"
  - name: "Vishnuvasan Raghuraman"
    roles:
    - "contributor"
    info:
      github: "vishnu-vasan"
  keywords:
  - "single-cell"
  - "cell-cell communication"
  - "openproblems"
  - "benchmark"
  license: "MIT"
  organization: "openproblems-bio"
  references:
    doi:
    - "10.1038/s41467-022-30755-0"
  links:
    repository: "https://github.com/openproblems-bio/task_cell_cell_communication"
    docker_registry: "ghcr.io"
    issue_tracker: "https://github.com/openproblems-bio/task_cell_cell_communication/issues"
