name: singlecell_broadinstitute
namespace: datasets/loaders
argument_groups:
  - name: Inputs
    arguments:
      - type: file
        name: --raw_data_dir
        description: |
          Path to the single-cell dataset dir.

          This directory is obtained by browsing one of the datasets on the single cell broad institute website and clicking 'Bulk download' and downloading the curl config file but not yet downloading the individual files.

          Example: https://singlecell.broadinstitute.org/single_cell/study/SCP2162/slide-tags-snrna-seq-on-mouse-hippocampus#study-download
        example: resources/raw_data/singlecell_broadinstitute/SCP2167
        required: true
        direction: input
  - name: Metadata
    arguments:
      - name: "--dataset_id"
        type: string
        description: Unique identifier for the dataset.
        required: true
      - name: "--dataset_name"
        type: string
        description: Nicely formatted name.
        required: true
      - name: "--dataset_url"
        type: string
        description: Link to the original source of the dataset.
        required: false
      - name: "--dataset_reference"
        type: string
        description: Bibtex reference of the paper in which the dataset was published.
        required: false
      - name: "--dataset_summary"
        type: string
        description: Short description of the dataset.
        required: true
      - name: "--dataset_description"
        type: string
        description: Long description of the dataset.
        required: true
      - name: "--dataset_organism"
        type: string
        description: The organism of the dataset.
        required: false
  - name: Outputs
    arguments:
    - name: --output
      description: "The downloaded dataset with metadata in uns."
      required: true
      direction: output
      __merge__: /src/api/file_common_spatial.yaml
resources:
  - type: python_script
    path: script.py
test_resources:
  - type: python_script
    path: /common/component_tests/run_and_check_output.py
engines:
  - type: docker
    image: openproblems/base_python:1.0.0
runners:
  - type: executable
  - type: nextflow