__merge__: /src/api/comp_dataset_loader.yaml

name: download
resources:
  - type: python_script
    path: script.py
engines:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.4
runners:
  - type: executable
  - type: nextflow